### ISSUE TITLE
Warp function for points in the no overlap region of the src point cloud ?

### ISSUE THREAD

**Issue by 2019EPWL** [qinzheng93/GraphSCNet#1]
Hi, I have a question about the teaser figure in the GraphSCNet paper. The warp function (10) is defined based on the predicted inlier correspondences. So, that means the paper doesn't deal with the outlier points, but the teaser and results figures show the dense shape reconstruction mesh, I am confused about that.

**Comment by qinzheng93** [comment]
Yes, it is very difficult to accurately infer the motion of the outlier points as there are no inlier correspondences within them. So the motion of these points is mainly constraint (or **guessed**, which I prefer) by the ARAP term in the N-ICP algorithm. The problem is more severe in low-overlap scenes.

BTW, the teaser shows point clouds, not meshes.

**Comment by 2019EPWL** [comment]
So the EPE, ACCS, and ACCR in the result table are only calculated on the predicted inliers, not on the all src point cloud.

**Comment by qinzheng93** [comment]
No, following NDP, the metrics are computed on ALL points.
